-- MySQL Script generated by MySQL Workbench
-- Fri Aug  8 12:06:31 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`RESPONSAVEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RESPONSAVEL` (
  `ID` INT NOT NULL,
  `NOME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ALUNO` (
  `ID` INT NOT NULL,
  `NOME` VARCHAR(255) NOT NULL,
  `RESPONSAVEL_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ALUNO_RESPONSAVEL_idx` (`RESPONSAVEL_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ALUNO_RESPONSAVEL`
    FOREIGN KEY (`RESPONSAVEL_ID`)
    REFERENCES `mydb`.`RESPONSAVEL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CURSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CURSO` (
  `ID` INT NOT NULL,
  `NOME` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MATRICULA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MATRICULA` (
  `ID` INT NOT NULL,
  `DATA_MATRICULA` DATE NOT NULL,
  `ALUNO_ID` INT NOT NULL,
  `CURSO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_MATRICULA_ALUNO1_idx` (`ALUNO_ID` ASC) VISIBLE,
  INDEX `fk_MATRICULA_CURSO1_idx` (`CURSO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_MATRICULA_ALUNO1`
    FOREIGN KEY (`ALUNO_ID`)
    REFERENCES `mydb`.`ALUNO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATRICULA_CURSO1`
    FOREIGN KEY (`CURSO_ID`)
    REFERENCES `mydb`.`CURSO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROFESSOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROFESSOR` (
  `ID` INT NOT NULL,
  `NOME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAGAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PAGAMENTO` (
  `ID` INT NOT NULL,
  `VALOR` DOUBLE NOT NULL,
  `DATA_PAGAMENTO` DATE NOT NULL,
  `STATUS` VARCHAR(10) NOT NULL,
  `ALUNO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PAGAMENTO_ALUNO1_idx` (`ALUNO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PAGAMENTO_ALUNO1`
    FOREIGN KEY (`ALUNO_ID`)
    REFERENCES `mydb`.`ALUNO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DISCIPLINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DISCIPLINA` (
  `ID` INT NOT NULL,
  `NOME` VARCHAR(150) NOT NULL,
  `PROFESSOR_ID` INT NOT NULL,
  `CURSO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_DISCIPLINA_PROFESSOR1_idx` (`PROFESSOR_ID` ASC) VISIBLE,
  INDEX `fk_DISCIPLINA_CURSO1_idx` (`CURSO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_DISCIPLINA_PROFESSOR1`
    FOREIGN KEY (`PROFESSOR_ID`)
    REFERENCES `mydb`.`PROFESSOR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DISCIPLINA_CURSO1`
    FOREIGN KEY (`CURSO_ID`)
    REFERENCES `mydb`.`CURSO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TURMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TURMA` (
  `ID` INT NOT NULL,
  `NOME_TURMA` VARCHAR(100) NOT NULL,
  `ANO` INT NOT NULL,
  `CURSO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TURMA_CURSO1_idx` (`CURSO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TURMA_CURSO1`
    FOREIGN KEY (`CURSO_ID`)
    REFERENCES `mydb`.`CURSO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
