-- Criação da tabela Responsavel
CREATE TABLE RESPONSAVEL (
    ID_RESPONSAVEL NUMBER(38,0) NOT NULL,
    NOME VARCHAR2(255 BYTE) NOT NULL,
    PRIMARY KEY (ID_RESPONSAVEL)
);

-- Criação da tabela Aluno
CREATE TABLE ALUNO (
    ID_ALUNO NUMBER(38,0) NOT NULL,
    NOME VARCHAR2(255 BYTE) NOT NULL,
    RESPONSAVEL_ID NUMBER(38,0),
    PRIMARY KEY (ID_ALUNO),
    FOREIGN KEY (RESPONSAVEL_ID) REFERENCES RESPONSAVEL(ID_RESPONSAVEL)
);

-- Criação da tabela Curso
CREATE TABLE CURSO (
    ID_CURSO NUMBER(38,0) NOT NULL,
    NOME VARCHAR2(150 BYTE) NOT NULL,
    PRIMARY KEY (ID_CURSO)
);

-- Criação da tabela Professor
CREATE TABLE PROFESSOR (
    ID_PROFESSOR NUMBER(38,0) NOT NULL,
    NOME VARCHAR2(255 BYTE) NOT NULL,
    PRIMARY KEY (ID_PROFESSOR)
);

-- Criação da tabela Disciplina
CREATE TABLE DISCIPLINA (
    ID_DISCIPLINA NUMBER(38,0) NOT NULL,
    NOME VARCHAR2(150 BYTE) NOT NULL,
    PROFESSOR_ID NUMBER(38,0),
    CURSO_ID NUMBER(38,0),
    PRIMARY KEY (ID_DISCIPLINA),
    FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSOR(ID_PROFESSOR),
    FOREIGN KEY (CURSO_ID) REFERENCES CURSO(ID_CURSO)
);

-- Criação da tabela Matricula
CREATE TABLE MATRICULA (
    ID_MATRICULA NUMBER(38,0) NOT NULL,
    DATA_MATRICULA DATE NOT NULL,
    ALUNO_ID NUMBER(38,0),
    CURSO_ID NUMBER(38,0),
    PRIMARY KEY (ID_MATRICULA),
    FOREIGN KEY (ALUNO_ID) REFERENCES ALUNO(ID_ALUNO),
    FOREIGN KEY (CURSO_ID) REFERENCES CURSO(ID_CURSO)
);

-- Criação da tabela Pagamento
CREATE TABLE PAGAMENTO (
    ID_PAGAMENTO NUMBER(38,0) NOT NULL,
    VALOR NUMBER(10,2) NOT NULL,
    DATA_PAGAMENTO DATE NOT NULL,
    STATUS VARCHAR2(10 BYTE) NOT NULL,
    ALUNO_ID NUMBER(38,0),
    PRIMARY KEY (ID_PAGAMENTO),
    FOREIGN KEY (ALUNO_ID) REFERENCES ALUNO(ID_ALUNO)
);

-- Criação da tabela Turma
CREATE TABLE TURMA (
    ID_TURMA NUMBER(38,0) NOT NULL,
    NOME_TURMA VARCHAR2(100 BYTE) NOT NULL,
    ANO NUMBER(38,0),
    CURSO_ID NUMBER(38,0),
    PRIMARY KEY (ID_TURMA),
    FOREIGN KEY (CURSO_ID) REFERENCES CURSO(ID_CURSO)
);
